### ISSUE TITLE
pnpm run build 时，包类型报错

### ISSUE THREAD

**Issue by wjcms** [dishait/vite-plugin-vue-meta-layouts#1]
node_modules/.pnpm/registry.npmmirror.com+vite-plugin-vue-meta-layouts@0.0.2_vue-router@4.0.14/node_modules/vite-plugin-vue-meta-layouts/client.d.ts:2:1 - error TS1185: Merge conflict marker encountered.

2 <<<<<<< HEAD
  ~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+vite-plugin-vue-meta-layouts@0.0.2_vue-router@4.0.14/node_modules/vite-plugin-vue-meta-layouts/client.d.ts:20:1 - error TS1185: Merge conflict marker encountered.

20 =======
   ~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+vite-plugin-vue-meta-layouts@0.0.2_vue-router@4.0.14/node_modules/vite-plugin-vue-meta-layouts/client.d.ts:23:1 - error TS1185: Merge conflict marker encountered.

23 >>>>>>> d6bcf7a6132315f2cf7b7f16b3cc5d47d56cb093
   ~~~~~~~


Found 3 errors in the same file, starting at: node_modules/.pnpm/registry.npmmirror.com+vite-plugin-vue-meta-layouts@0.0.2_vue-router@4.0.14/node_modules/vite-plugin-vue-meta-layouts/client.d.ts:2

 ELIFECYCLE  Command failed with exit code 2.

**Comment by markthree** [comment]
@wjcms 靓仔你好，问题已修复，可以更新 `vite-plugin-vue-meta-layouts` 依赖到 `0.0.8`。同时如果你是使用 `npm create vite` 的方式创建的项目，可以在 `tsconfig.json` 中的 `compilerOptions` 中设置 `skipLibCheck` 为 `true` 跳过包检测。或者在 `package.json` 中的 `scripts` 中的 `build` 改为为 `vite build`。
