### ISSUE TITLE
0.3.2 does not include code in publish

### ISSUE THREAD

**Issue by kingyue737** [dishait/vite-plugin-vue-meta-layouts#11]
https://www.unpkg.com/browse/vite-plugin-vue-meta-layouts@0.3.2/

No `dist` in `node_modules/vite-plugin-vue-meta-layouts`

![image](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/40021217/dbf44d93-3583-4610-86b2-2ff5eb5a3885)

**Comment by markthree** [comment]
@kingyue737 I have checked and I will republish the version

**Comment by markthree** [comment]
@kingyue737 Has been republished to [0.3.3](https://www.unpkg.com/browse/vite-plugin-vue-meta-layouts@0.3.3/)，Thank you for your reminder
