### ISSUE TITLE
路径出错了

### ISSUE THREAD

**Issue by 2815261401** [dishait/vite-plugin-vue-meta-layouts#13]
![image](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/71112636/a40f694e-b75a-46a5-a3a3-4d6245bffcdf)
https://www.npmjs.com/package/vite-plugin-vue-meta-layouts?activeTab=code
路径出错了

**Comment by markthree** [comment]
@2815261401 靓仔，已重新发布，请下载最新版本 ^0.4.1
