### ISSUE TITLE
配置失效

### ISSUE THREAD

**Issue by nigiwen** [dishait/vite-plugin-vue-meta-layouts#15]
当进入layout: empty页面时，还是使用默认index布局

![image](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/67454874/a23ed56b-691c-4508-bb73-dee2d8503951)
![image](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/67454874/4f30a366-dddb-4e2f-89db-26aa1a115836)
![image](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/67454874/b34949f1-cc76-48a3-9f64-59984b239c75)

**Comment by wen403** [comment]
pagesDirs 参数用不了

**Comment by markthree** [comment]
@wen403 靓仔，未复现哦，请提供最小测试仓库

**Comment by markthree** [comment]
> pagesDirs 参数用不了

[vite-plugin-vue-meta-layouts](https://github.com/dishait/vite-plugin-vue-meta-layouts) 没有 `pagesDirs` 参数哦，具体可见 `README` 中的使用说明

**Comment by markthree** [comment]
很抱歉，靓仔，由于未提供最小复现仓库，只能先 close 了
