### ISSUE TITLE
文档中类型声明vite-plugin-vue-meta-plugin是不是写错了？

### ISSUE THREAD

**Issue by stovenlin** [dishait/vite-plugin-vue-meta-layouts#2]
{
	"compilerOptions": {
		"types": ["vite-plugin-vue-meta-plugin/client"]
	}
}
是不是应该是
{
	"compilerOptions": {
		"types": ["vite-plugin-vue-meta-layouts/client"]
	}
}

**Comment by markthree** [comment]
@stovenlin 靓仔你好，是的

**Comment by markthree** [comment]
@stovenlin  已处理，具体可见该提交 👉 [b7eb34](https://github.com/dishait/vite-plugin-vue-meta-layouts/commit/b7eb348cbd81b889d1df0a1883ac30b372aa0695)
