### ISSUE TITLE
设置布局函数 createRouter 在搭配 unplugin-vue-router 时出现异常

### ISSUE THREAD

**Issue by mote-ice** [dishait/vite-plugin-vue-meta-layouts#22]
这个问题在 v0.5.0 ，[修复route.meta.layout使用!==校验错误](https://github.com/dishait/vite-plugin-vue-meta-layouts/commit/0a751494c958c095add16c1ba764b5453d94533a) 后出现的问题

**Comment by markthree** [comment]
@mote-ice 已回滚，可以下载 v0.5.1
