### ISSUE TITLE
❓ Is this project maintained & up to date?

### ISSUE THREAD

**Issue by jd-solanki** [dishait/vite-plugin-vue-meta-layouts#6]
Hi 👋🏻 

I was trying to use [unplugin-vue-router](https://github.com/posva/unplugin-vue-router) and found that `vite-plugin-vue-layouts` has some issues and lib isn't well maintained (no regular releases & no respond from the author).

I noticed you were doing great job with PR & support.

Hence, I want to know is this project up to date or this is just for PR you made to the `vite-plugin-vue-layouts`?

Are you willing to maintain it in future?

**Comment by markthree** [comment]
@jd-solanki [The same implementation](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/111) is merged by vite-plugin-vue-layou)ts, but it's still not available because [vite-plugin-vue-layouts/issues/111](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/111)
