### ISSUE TITLE
每次跳转页面都会重复执行main.ts方法

### ISSUE THREAD

**Issue by kenny-yao** [dishait/vite-plugin-vue-meta-layouts#8]
项目：examples/unplugin-vue-router
首次进入首页，见下图：
![image](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/23625786/e0f7feff-6fc1-4096-afa4-14ae59dea55c)

在此进入其它页面，比如about，见下图：
![image](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/23625786/56f4cf9f-0a9f-44f8-b029-e6fbb6c4c582)

每次跳转页面，main.ts里面方法都重新执行了一遍

**Comment by markthree** [comment]
@kenny-yao 靓仔你好，你需要使用 `<router-link to="/">about</router-link>` 去跳转，而非浏览器导航栏。导航栏进入会进行应用的重新加载，非 `bug`
