### ISSUE TITLE
`virtual:meta-layouts` shows type declaration error.

### ISSUE THREAD

**Issue by premdasvm** [dishait/vite-plugin-vue-meta-layouts#9]
Hi,

I'm tryna use your package with `unplugin-vue-router`, everything is working fine, i can see the different layouts and all. but i can't seem to get rid of the type declaration error. 🥲

![Screenshot 2023-09-20 at 2 49 01 AM](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/14838550/8bf68f9d-dbae-4ace-841f-1bb5fd591853)

here is my `tsconfig.app.json`

```json
{
  "extends": ["@vue/tsconfig/tsconfig.json", "@vue/tsconfig/tsconfig.dom.json"],
  "include": [
    "env.d.ts",
    "src/**/*",
    "src/**/*.vue",
    "typed-router.d.ts",
    "auto-imports.d.ts",
    "components.d.ts"
  ],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["vite-plugin-vue-meta-layouts/client"]
  }
}
```

![Screenshot 2023-09-20 at 2 50 49 AM](https://github.com/dishait/vite-plugin-vue-meta-layouts/assets/14838550/24928dad-c4ba-4de9-9f2a-75d652dd6439)

For reference [Repo](https://github.com/premdasvm/vue-primevue-template)

**Comment by markthree** [comment]
@premdasvm Hi, I found out that there is a conflict between extends and compilerOptions types, commenting out extends solves the problem temporarily.

So far I haven't found a ts method that is compatible with your repo. 😭

**Comment by premdasvm** [comment]
@markthree commenting out the extends wouldn't affect anything else right?

**Comment by markthree** [comment]
@premdasvm I'm sorry, I'm busy with other work today, I think we can find some kind of configuration to be more compatible with this repo without having to change too many things。

A temporary ignore solution is ↓

```ts
// src/router/index.ts
import { routes as fileRoutes } from 'vue-router/auto/routes'
import { createRouter, createWebHistory } from 'vue-router'
// @ts-ignore
import { setupLayouts } from 'virtual:meta-layouts'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  // @ts-ignore
  routes: setupLayouts(fileRoutes)
})

export default router
```

```json5
// tsconfig.app.json
{
  "extends": ["@vue/tsconfig/tsconfig.json", "@vue/tsconfig/tsconfig.dom.json"],
  "include": [
    "env.d.ts",
    "src/**/*",
    "src/**/*.vue",
    "typed-router.d.ts",
    "auto-imports.d.ts",
    "components.d.ts"
  ],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
    // "types": ["vite-plugin-vue-meta-layouts/client"]
  }
}
```

**Comment by markthree** [comment]
@premdasvm Hi，I took a closer look at the repo, and adding the following option fixes it perfectly without making too many changes.

```diff
// tsconfig.app.json
{
  "extends": ["@vue/tsconfig/tsconfig.json", "@vue/tsconfig/tsconfig.dom.json"],
  "include": [
    "env.d.ts",
    "src/**/*",
    "src/**/*.vue",
    "typed-router.d.ts",
    "auto-imports.d.ts",
    "components.d.ts"
  ],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
+   "moduleResolution": "Node",
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["vite-plugin-vue-meta-layouts/client"]
  }
}
```

**Comment by PWie** [comment]
The actual solution to this is to declare types entry for `/client` in package.json:

```typescript
// package.json
{
   // ...
  "exports": {
    "./client": {
      "types": "./client.d.ts"
    },
    "./*": "./*",
    ".": {
      "require": "./dist/index.cjs",
      "import": "./dist/index.mjs",
      "types": "./dist/index.d.ts"
    }
  },
}
```
